#  importing the libraries
# reading the netflix file into dataframe

In [2]:
import numpy as np
import pandas as pd

df=pd.read_excel('netflix.xlsx')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   object
 2   title         6234 non-null   object
 3   director      4265 non-null   object
 4   cast          5664 non-null   object
 5   country       5758 non-null   object
 6   release_year  6234 non-null   int64
 7   rating        6224 non-null   object
 8   duration      6234 non-null   object
 9   listed_in     6234 non-null   object
dtypes: int64(2), object(8)
memory usage: 487.2+ KB

# 1.    Select TV Show released in year 2019

In [4]:
df[(df.release_year == 2019) & (df.type=='TV Show')]

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
34,80221550,TV Show,Archibald's Next Big Thing,NaN,"Tony Hale, Rosamund Pike, Jordan Fisher, Chels...",NaN,2019,TV-Y7,1 Season,"Kids' TV, TV Comedies"
39,80178151,TV Show,The Spy,NaN,"Sacha Baron Cohen, Noah Emmerich, Hadar Ratzon...",France,2019,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers"
99,80225885,TV Show,Bard of Blood,NaN,"Emraan Hashmi, Viineet Kumar, Sobhita Dhulipal...",India,2019,TV-MA,1 Season,"International TV Shows, TV Action & Adventure,..."
101,80218107,TV Show,Dragons: Rescue Riders,NaN,"Nicolas Cantu, Brennley Brown, Zach Callison, ...",NaN,2019,TV-Y,1 Season,"Kids' TV, TV Comedies"
103,80220715,TV Show,Skylines,NaN,"Edin Hasanovic, Peri Baumeister, Murathan Musl...",NaN,2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas"
...,...,...,...,...,...,...,...,...,...,...
6198,80189829,TV Show,The Protector,NaN,"Çağatay Ulusoy, Ayça Ayşin Turan, Hazar Ergüçl...",Turkey,2019,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
6204,80091341,TV Show,Cuckoo,NaN,"Andy Samberg, Taylor Lautner, Greg Davies, Hel...",United Kingdom,2019,TV-14,5 Seasons,"British TV Shows, International TV Shows, TV C..."
6206,80173174,TV Show,Samantha!,NaN,"Emmanuelle Araújo, Douglas Silva, Sabrina Nona...",Brazil,2019,TV-MA,2 Seasons,"International TV Shows, TV Comedies"
6215,80066227,TV Show,Crazy Ex-Girlfriend,NaN,"Rachel Bloom, Vincent Rodriguez III, Santino F...",United States,2019,TV-14,4 Seasons,"Romantic TV Shows, TV Comedies"
6219,80186475,TV Show,Pokémon the Series,NaN,"Sarah Natochenny, Laurie Hymes, Jessica Paquet...",Japan,2019,TV-Y7-FV,2 Seasons,"Anime Series, Kids' TV"

# 2.    Select Movies between year 2018 to 2020

In [5]:
df[((df.release_year >= 2018) & (df.release_year <= 2020)) & (df.type=='Movie')]

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies"
27,80203094,Movie,City of Joy,Madeleine Gavin,NaN,"United States,",2018,TV-MA,77 min,Documentaries
30,80988892,Movie,Next Gen,"Kevin R. Adams, Joe Ksander","John Krasinski, Charlyne Yi, Jason Sudeikis, M...","China, Canada, United States",2018,TV-PG,106 min,"Children & Family Movies, Comedies, Sci-Fi & F..."
31,80239639,Movie,Sierra Burgess Is A Loser,Ian Samuels,"Shannon Purser, Kristine Froseth, RJ Cyler, No...",United States,2018,PG-13,106 min,"Comedies, Romantic Movies"
32,80159586,Movie,The Most Assassinated Woman in the World,Franck Ribière,"Anna Mouglalis, Niels Schneider, André Wilms, ...","Belgium, United Kingdom, United States",2018,TV-MA,102 min,"Dramas, International Movies, Thrillers"
...,...,...,...,...,...,...,...,...,...,...
5476,80210602,Movie,I Am Maris,Laura VanZee Taylor,Maris Degener,United States,2018,TV-14,54 min,Documentaries
5477,81088283,Movie,Jesus: Countdown to Calvary,Gerry Hoban,Hugh Bonneville,"Ireland, United States, France",2018,TV-14,53 min,"Documentaries, Faith & Spirituality"
5485,81052280,Movie,Pinky Memsaab,Shazia Ali Khan,"Hajira Yamin, Kiran Malik, Adnan Jaffar, Sunny...","Pakistan, United Arab Emirates",2018,TV-14,124 min,"Dramas, Independent Movies, International Movies"
5497,81088284,Movie,The World's Most Wanted Animal,Victoria Bromley,Maria Diekmann,United Kingdom,2018,TV-PG,53 min,Documentaries
5520,80244992,Movie,Ethirmarai,NaN,"Ramanathan, Rakesh",India,2018,TV-14,91 min,"International Movies, Music & Musicals, Thrillers"

# 3.    Select shows aired only in United states

In [6]:
df[df.country=='United States']

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,2017,TV-MA,1 Season,"Docuseries, Science & Nature TV"
20,80060297,Movie,Manhattan Romance,Tom O'Brien,"Tom O'Brien, Katherine Waterston, Caitlin Fitz...",United States,2014,TV-14,98 min,"Comedies, Independent Movies, Romantic Movies"
...,...,...,...,...,...,...,...,...,...,...
6225,70153412,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies"
6226,70243132,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh..."
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies"

# 4.    Select cast of the TV shows  telecasted in year 2019 and had rating R

In [7]:
df[(df.release_year==2019) & (df.rating=='R')]['cast']

87      Nikolaj Coster-Waldau, Carice van Houten, Eriq...
125     Aml Ameen, Rhea Seehorn, Roxanne McKee, Urs Re...
529     Eddie Murphy, Wesley Snipes, Keegan-Michael Ke...
654     Meryl Streep, Gary Oldman, Antonio Banderas, S...
1038    Michael Jai White, Vince Swann, Barry Bostwick...
1100    Robert De Niro, Al Pacino, Joe Pesci, Harvey K...
1264    Alicia Vikander, Riley Keough, Naoki Kobayashi...
1419    Timothée Chalamet, Joel Edgerton, Robert Patti...
1625    Zac Efron, Lily Collins, Kaya Scodelario, Jeff...
1773    Joe Anderson, William Baldwin, Donald Sutherla...
1807    Amy Poehler, Maya Rudolph, Ana Gasteyer, Rache...
2051    Kevin Costner, Woody Harrelson, Kathy Bates, J...
2239    Ben Affleck, Oscar Isaac, Charlie Hunnam, Pedr...
2431                                                  NaN
2457    Penélope Cruz, Javier Bardem, Ricardo Darín, E...
3381    Laura Marano, Vanessa Marano, Christopher Tava...
4042    Jake Gyllenhaal, Rene Russo, Zawe Ashton, Toni...
4132    Scarlett Johansson, Adam Driver, Laura Dern, A...
4351    Amy Manson, Dominic Mafham, Luke Allen-Gale, J...
4354    Amaury Nolasco, Devon Sawa, Robert Patrick, Je...
4377    Michael Ealy, Jesse Williams, Nicole Beharie, ...
4579    Ryan Reynolds, Mélanie Laurent, Corey Hawkins,...
4905                                                  NaN
5363    Gina Rodriguez, Brittany Snow, DeWanda Wise, L...
Name: cast, dtype: object

# 5.    Drop column show_id

In [8]:
df.drop(['show_id'], axis = 1, inplace = True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          6234 non-null   object
 1   title         6234 non-null   object
 2   director      4265 non-null   object
 3   cast          5664 non-null   object
 4   country       5758 non-null   object
 5   release_year  6234 non-null   int64
 6   rating        6224 non-null   object
 7   duration      6234 non-null   object
 8   listed_in     6234 non-null   object
 9   duration_min  6234 non-null   object
dtypes: int64(1), object(9)
memory usage: 487.2+ KB

# 6.    Add column duration_min such that it’s type is numeric [use column duration]

In [9]:
df['duration_min'] = df.duration.apply(lambda x : x.split()[0])

In [11]:
df.head(25)

,type,title,director,cast,country,release_year,rating,duration,listed_in,duration_min
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies",90
1,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016,TV-MA,94 min,Stand-Up Comedy,94
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV,1
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV,1
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies,99
5,TV Show,Apaches,NaN,"Alberto Ammann, Eloy Azorín, Verónica Echegui,...",Spain,2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",1
6,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers",110
7,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,2017,TV-MA,60 min,Stand-Up Comedy,60
8,TV Show,Fire Chasers,NaN,NaN,United States,2017,TV-MA,1 Season,"Docuseries, Science & Nature TV",1
9,Movie,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden",2014,R,90 min,"Action & Adventure, Thrillers",90
10,Movie,Joaquín Reyes: Una y no más,José Miguel Contreras,Joaquín Reyes,NaN,2017,TV-MA,78 min,Stand-Up Comedy,78
11,Movie,Kidnapping Mr. Heineken,Daniel Alfredson,"Jim Sturgess, Sam Worthington, Ryan Kwanten, A...","Netherlands, Belgium, United Kingdom, United S...",2015,R,95 min,"Action & Adventure, Dramas, International Movies",95
12,Movie,Krish Trish and Baltiboy,NaN,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",NaN,2009,TV-Y7,58 min,Children & Family Movies,58
13,Movie,Krish Trish and Baltiboy: Battle of Wits,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Baba S...",NaN,2013,TV-Y7,62 min,Children & Family Movies,62
14,Movie,Krish Trish and Baltiboy: Best Friends Forever,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Deepak...",NaN,2016,TV-Y,65 min,Children & Family Movies,65
15,Movie,Krish Trish and Baltiboy: Comics of India,Tilak Shetty,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",NaN,2012,TV-Y7,61 min,Children & Family Movies,61
16,Movie,Krish Trish and Baltiboy: Oversmartness Never ...,Tilak Shetty,"Rishi Gambhir, Smita Malhotra, Deepak Chachra",NaN,2017,TV-Y7,65 min,Children & Family Movies,65
17,Movie,Krish Trish and Baltiboy: Part II,NaN,"Damandeep Singh Baggan, Smita Malhotra, Baba S...",NaN,2010,TV-Y7,58 min,Children & Family Movies,58
18,Movie,Krish Trish and Baltiboy: The Greatest Trick,"Munjal Shroff, Tilak Shetty","Damandeep Singh Baggan, Smita Malhotra, Baba S...",NaN,2013,TV-Y7,60 min,Children & Family Movies,60
19,Movie,Love,Gaspar Noé,"Karl Glusman, Klara Kristin, Aomi Muyock, Ugo ...","France, Belgium",2015,NR,135 min,"Cult Movies, Dramas, Independent Movies",135
20,Movie,Manhattan Romance,Tom O'Brien,"Tom O'Brien, Katherine Waterston, Caitlin Fitz...",United States,2014,TV-14,98 min,"Comedies, Independent Movies, Romantic Movies",98
21,Movie,Moonwalkers,Antoine Bardou-Jacquet,"Ron Perlman, Rupert Grint, Robert Sheehan, Ste...","France, Belgium",2015,R,96 min,"Action & Adventure, Comedies, International Mo...",96
22,Movie,Rolling Papers,Mitch Dickman,NaN,"United States, Uruguay",2015,TV-MA,79 min,Documentaries,79
23,Movie,Stonehearst Asylum,Brad Anderson,"Kate Beckinsale, Jim Sturgess, David Thewlis, ...",United States,2014,PG-13,113 min,"Horror Movies, Thrillers",113
24,Movie,The Runner,Austin Stark,"Nicolas Cage, Sarah Paulson, Connie Nielsen, W...",United States,2015,R,90 min,"Dramas, Independent Movies",90